# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191030_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('update_email', '修改邮箱'), ('register', '注册'), ('forget', '找回密码')], max_length=12, verbose_name='验证类型'),
        ),
    ]
